### ISSUE TITLE
RFC: put all template values into attributes

### ISSUE THREAD

**Issue by willejs** [michaelklishin/cassandra-chef-cookbook#148]
The cassandra.yaml file is heavily templated and has many hard coded values in it. The config file is large, and has many possible values and combinations.

I don't want to submit a bunch of pull requests for these, and i don't care about the comments in the file either. (Others might care about these comments, we can put them into the config.rb attributes file if people wish.)

I am proposing that we do away with the keys, and comments in the erb template and instead generate the yaml from a hash in the attributes.

This way we can easily manage the hundred or so config values in attributes, and add additional settings that are not in the template that can be set.

What are peoples thoughts on this? I will get to work on a PR if people are in agreement.

**Comment by michaelklishin** [comment]
Is this still relevant?

**Comment by willejs** [comment]
I think I decided that there were too many variations between versions of
Cassandra. I'm trying to think of a more elegant way to template these per
version, but I will probably just specify a template in a wrapper
cookbook...

**Comment by vkhatri** [comment]
i will take a stab at it this week. i am thinking about adding an array attribute to keep a list of attributes for cassandra.yaml against which i can validate the attributes specified the attributes and ignore if user added unintentionally. this way user can add their own attributes if missing any, until it gets added to this cookbook.

**Comment by vkhatri** [comment]
@michaelklishin i am thinking to move all config attributes to a new attribute file `attributes/config.rb` under attribute `default['cassandra']['config']`.

like default common attributes:

```ruby
default['cassandra']['config']['attribute_name'] = value
```
and conditional attributes for specific version
```ruby
if version =~ /2.1/
  default['cassandra']['config']['attrirbute_name'] = value
elsif version =~ /2.1/
  default['cassandra']['config']['attrirbute_name'] = value
...
end
```

`cassandra.yaml.erb` template resource would become:

```ruby
variables node['cassandra']['config'].to_yaml
```
let me know if sound like a good idea.

**Comment by michaelklishin** [comment]
@vkhatri this sounds reasonable. We may have to bump the version to `4.0` if we introduce a breaking change like that.

**Comment by vkhatri** [comment]
@michaelklishin alright! i will get started.

**Comment by michaelklishin** [comment]
This is done in master.

**Comment by michaelklishin** [comment]
This change broke so many things (intentionally and unintentionally) so badly that I'm going to become a lot more conservative with sweeping changes like this.
