### ISSUE TITLE
Add multiple data_dir locations (JBOD Cassandra 1.2+)

### ISSUE THREAD

**Issue by felka** [michaelklishin/cassandra-chef-cookbook#154]
For C* 1.2+ it will be nice to have option to define array of data_dirs and template will populate multiple locations.

**Comment by michaelklishin** [comment]
Feel free to submit a pull request.

Why does this not apply to later versions, by the way?

**Comment by vkhatri** [comment]
i think it is broken currently for recipe `tarball`, as `node['cassandra']['data_dir']` gets evaluated as an array which is not acceptable for `directory` resource.

looking into it.

**Comment by michaelklishin** [comment]
Fixed by #202.
