### ISSUE TITLE
FC048 should not evaluate 'system' in user and group resources

### ISSUE THREAD

**Issue by felka** [michaelklishin/cassandra-chef-cookbook#158]
Foodcritic reads users.rb and fails on "system" keyword. FC048 has an exception for user and group resources, but only when they has a boolean value. Once node attribute assign it fails. 
I opened issue in foodcritic to disable FC048 evaluation in user and group.

**Comment by michaelklishin** [comment]
Sorry, I'm not sure what we should do then?

**Comment by felka** [comment]
You may temporary disable rule by using "# ~FC048" right after the "system" statement
