### ISSUE TITLE
[cassandra][vnode] = 'true' creates invalid cassandra.yaml

### ISSUE THREAD

**Issue by karlbunnell** [michaelklishin/cassandra-chef-cookbook#165]
This sets num_tokens: true in cassandra.yaml which is invalid. This shouldn't be a true/false value. It should be a number. Correct?
Perhaps this was the intent? Set to false for num_tokens to be commented out and set to the num_tokens desired if vnode configuration is desired?

**Comment by vkhatri** [comment]
@karlbunnell that is correct, feel free to submit a PR
