### ISSUE TITLE
Authentication for opscenter

### ISSUE THREAD

**Issue by rnekkanti** [michaelklishin/cassandra-chef-cookbook#174]
I am running opscenter-free on Ubuntu 14.04. According to the opscenter 5.10 documentation, for enabling authentication, the authentication section in opscenterd.conf should have enabled set to true.

[authentication]
enabled=True

The template opscenterd.conf.erb does not have this set. It is not sent even as an attribute.

http://www.datastax.com/documentation/opscenter/5.1/opsc/configure/opscEnablingAuth.html

**Comment by michaelklishin** [comment]
@rnekkanti sounds like a low-hanging fruit. Do you want to work on a pull request?

**Comment by rnekkanti** [comment]
Submitted the pull request.

**Comment by michaelklishin** [comment]
Fixed by #177.
