### ISSUE TITLE
Add support for '-Dcassandra.boot_without_jna=true' for running C* >= 2.1.0 in low-memory environments

### ISSUE THREAD

**Issue by zznate** [michaelklishin/cassandra-chef-cookbook#178]
JNA attempts to allocate at least ~ 1024mb regardless of jvm settings. This is somewhat described in this issue: 
https://issues.apache.org/jira/browse/CASSANDRA-6575 

And in CCM: 
https://github.com/pcmanus/ccm/issues/97

**Comment by michaelklishin** [comment]
Fixed by #179. Thank you, @zznate!
