### ISSUE TITLE
Setup fails for Cassandra 2.1 due to conflict with the default configuration

### ISSUE THREAD

**Issue by vervas** [michaelklishin/cassandra-chef-cookbook#188]
The default configuration since version 2.0 sets the `num_tokens` to 256, with it being the recommended value since 1.2. However the template comments this line out which sets the value to 1 by default. Since the debian installation starts the service with the default value to 256 but then this is uncommented, hence set to 1, the service then restarts with the new value breaking like this:
```
ERROR [main] 2015-06-08 14:47:51,512 CassandraDaemon.java:398 - Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: Cannot change the number of tokens from 256 to 1
```

This requires deleting the data folder which is not a good idea. I submitted PR #187 with a proposal to switch to new default values.

**Comment by michaelklishin** [comment]
#187 is merged, thank you!

**Comment by vervas** [comment]
cheers :)
