### ISSUE TITLE
The cookbook name is 'cassandra-dse' but the `templates_cookbook` is 'cassandra'

### ISSUE THREAD

**Issue by chrisduong** [michaelklishin/cassandra-chef-cookbook#196]
Hi,

The cookbook name is 'cassandra-dse' but the `templates_cookbook` is 'cassandra'. This make Chef look for the template file in `cassandra cookbook` instead of `cassandra-dse cookbook`. That's why Chef says 

Chef::Exceptions::CookbookNotFound
           ----------------------------------
           Cookbook cassandra not found. If you're loading cassandra from another cookbook, make sure you configure the dependency in your metadata

To fix it, I have to override the attribute default['cassandra']['templates_cookbook'] = 'cassandra-dse'

**Comment by chrisduong** [comment]
Sorry, I've just pulled the lastest tag, and see that you rename cookbook to `cassandra` so it won't be an issue anymore.

**Comment by michaelklishin** [comment]
Yes, this is fixed in `v3.2.0`. We'll be adding more tests to make sure they catch this earlier.
