### ISSUE TITLE
Chef search support for seeds

### ISSUE THREAD

**Issue by michaelklishin** [michaelklishin/cassandra-chef-cookbook#204]
Configuring seed nodes can be a pain in the neck when `knife bootstrap` isn't used, e.g. when nodes are booted from AMIs by an autoscaling group on EC2.

We should use Chef search to locate nodes with the role `cassandra` and fall back to the current value (node's IP address) if none found.

@vkhatri thoughts?

**Comment by vkhatri** [comment]
@michaelklishin this sound great and a great value add missing at the moment, especially for auto scaling clusters.

i can help if you have not already started working on it.

**Comment by michaelklishin** [comment]
I'm going to give this a shot this evening.
