### ISSUE TITLE
`set_fd_limit` block hangs on provisioning

### ISSUE THREAD

**Issue by vervas** [michaelklishin/cassandra-chef-cookbook#206]
The block introduced on commit https://github.com/michaelklishin/cassandra-chef-cookbook/commit/8330f0181539491affd1c6b9ea6f55b5408a3655 seems to cause provisioning to hang for a long time. Using vagrant and kitchen with a ubuntu-14.04 box.

**Comment by michaelklishin** [comment]
I have no idea why editing a file can take a long time but `block` resources support limiting the number of retries and retry delay. We should use both (e.g. retry every 1 second, 15 times).

**Comment by msilvey** [comment]
put the retries in at https://github.com/michaelklishin/cassandra-chef-cookbook/pull/249 . Not sure this will actually fix the issue as I'm not sure I read the retry_delay as a timeout so much as an interval between attempts.

**Comment by michaelklishin** [comment]
Fixed by @msilvey in #249.
