### ISSUE TITLE
jamm lib is always added in cassandra-env.sh

### ISSUE THREAD

**Issue by vkhatri** [michaelklishin/cassandra-chef-cookbook#208]
regardless of node attribute `default['cassandra']['setup_jamm']`, configuration file `cassandra-env.sh` always add `jamm` jar file which causes issue to C* service.

it impacts install method `tarball`, need to check for `datastax`.

will be submitting a PR for this soon.

**Comment by vkhatri** [comment]
currently C* tarball ships with its own `jamm` jar file and it seems it gets added to the java `class path` by default. i am not sure the impact of having two `jamm` jar files in the java `class path`.

cookbook should delete the default jar (which could be tricky) or use the provided one.

but regardless, template `cassandra-env.sh` should not add `jamm` lib if `setup_jamm` is not set.

**Comment by michaelklishin** [comment]
Having two jamm jars on the class path can lead to the wrong version being loaded. We should definitely avoid it.

**Comment by vkhatri** [comment]
agreed. i will check 2.1.x and older releases for packaged `jamm` jar. `setup_jamm` is required for releases without `jamm` jar.

i think this PR still stands for now, probably need to modify to setup `jamm` only for older releases which does not have `jamm` jar.

**Comment by vkhatri** [comment]
@michaelklishin `jamm` jar was added in C* version `0.8.0`. perhaps we can simply remove it from the cookbook.

**Comment by michaelklishin** [comment]
@vkhatri sorry, I don't see any PRs submitted. Is this still in play?

**Comment by vkhatri** [comment]
@michaelklishin sorry, i have not gotten time lately. i will submit PR, some time today.

**Comment by michaelklishin** [comment]
Fixed in master, thanks @vkhatri!
