### ISSUE TITLE
Tarball SHA256 shouldn't be required when installation method is not tarball

### ISSUE THREAD

**Issue by michaelklishin** [michaelklishin/cassandra-chef-cookbook#219]
Currently it is implicitly required, e.g. try clearing the sha256 helper and provision using `installation_method: "datastax"`.

**Comment by vkhatri** [comment]
@michaelklishin agreed, i will move it to `tarball` recipe.

**Comment by vkhatri** [comment]
@michaelklishin PR submitted.
