### ISSUE TITLE
optional purge older C* tarball archives

### ISSUE THREAD

**Issue by vkhatri** [michaelklishin/cassandra-chef-cookbook#222]
recipe `tarball` needs to modify to delete older C* archives.

attribute `default['cassandra']['tarball_purge']` would control the behavior with default value set to `false`.

**Comment by vkhatri** [comment]
@michaelklishin sorry, missed README update. will submit another PR for it.

**Comment by michaelklishin** [comment]
Fixed in https://github.com/vkhatri/cassandra-chef-cookbook/commit/1f2c4392a597b5a4c1a236f80c2156dd4ae3a75f.
