### ISSUE TITLE
New attributes for JVM GC Tuning are not in sync

### ISSUE THREAD

**Issue by miketheman** [michaelklishin/cassandra-chef-cookbook#247]
Introduced in #232 

This doesn't currently work as intended.
The attributes/default.rb file are:

    node['cassandra']['g1gc']
    node['cassandra']['gcdetail']

but the template is looking for:

    node['cassandra']['jvm']['g1gc']
    node['cassandra']['jvm']['gcdetail']

One or the other should be chosen. I'm leaning towards `node['cassandra']['jvm']['gcdetail']` - as it "namespaces" the settings.

This should definitely be fixed before 4.1.0 release.

**Comment by vkhatri** [comment]
PR #243 will resolve this. Will merge it today.

**Comment by miketheman** [comment]
@vkhatri Thanks@ I searched but didn't find, must have used the wrong words. Sorry for the additional issue.

**Comment by msilvey** [comment]
Should be able to close this with https://github.com/michaelklishin/cassandra-chef-cookbook/pull/243 merged.
