### ISSUE TITLE
4.0.0 does not respect tarball sha256sum

### ISSUE THREAD

**Issue by wsh** [michaelklishin/cassandra-chef-cookbook#251]
Compare line 61 of `tarball.rb` on `master` vs the 4.0 tag. This is fixed now, obviously, but a release is merited. I don't know about anyone else, but ~~this is a blocker for me because I'm trying to use the cookbook with version 3.0~~ (I'll just use what's on master).

**Comment by michaelklishin** [comment]
@wsh I wanted to release `4.1.0` with #246 in but fair enough, that can go into a later version.

**Comment by michaelklishin** [comment]
Closing in favour of #262.
