### ISSUE TITLE
Cassandra Datastax Enterprise 

### ISSUE THREAD

**Issue by nitdana** [michaelklishin/cassandra-chef-cookbook#252]
Hi,
I tried to deploy the DataStax Enterprise edition and after facing some difficulties due to lack of documentation, I wrote down the configuration that worked for me, Tested on Ubuntu 12.04.
Hope that you'll find it useful.

For installing the Cassandra enterprise package override the following attributes:
```
        "cassandra": {
            "package_name": "dse-full",
            "service_name": "dse"
        }
```
You’ll need to gather your credentials for the Datastax website and insert them in one of the following formats:
Option 1# - attributes in a role / environment / node:
```
        "cassandra": {
            "dse": {
                "credentials": {
                    "username": "%USERNAME%",
                    "password": "%PASSWORD%"
                }            
        }
```
Option 2# - using a data bag:
// You can use any name, item or entry name you’d like just make sure to create a matching data_bag file
```
        "cassandra": {
            "dse": {
                "credentials": {
                    "databag": {
                        "name": "cassandra",
                        "item": "main",
                        "entry": "entry"
                    }
                }
            }
        }
```

The data_bag (/data_bags/cassandra/main.json):
```
{
  "id": "main",
  "entry": {
    "username": "%USERNAME%",
    "password": "%PASSWORD%"
  }
}
```

**Comment by michaelklishin** [comment]
@nitdana thank you, how about you submit a pull request for README (where all of our docs currently are) under a separate section? Thank you.

**Comment by michaelklishin** [comment]
As of #253, this is in the README — thank you @nitdana!
