### ISSUE TITLE
DataStax Community 3.3 support

### ISSUE THREAD

**Issue by leicozit** [michaelklishin/cassandra-chef-cookbook#266]
The latest version of DataStax Distribution of Apache Cassandra 3.x is 3.3.  When you make changes to cookbook?

**Comment by michaelklishin** [comment]
@leicozit this is open source software. You can contribute the change instead of asking others to do a change you need.

**Comment by williamsjj** [comment]
@leicozit I've submitted a pull request (https://github.com/michaelklishin/cassandra-chef-cookbook/pull/276) that will enable you to install Cassandra > 3.0 (including 3.5.0).

If its accepted you'll just need to override these attributes in your wrapper cookbook/role:

```
normal['cassandra']['version'] = "3.x.0"
normal['cassandra']['release'] = ""
normal['cassandra']['jamm']['version'] = "0.3.1"
normal['cassandra']['package_name'] = "datastax-ddc"
normal['cassandra']['tools_package_name'] = "datastax-ddc-tools"
```

**Comment by michaelklishin** [comment]
The PR is in, thank you, @williamsjj!

**Comment by williamsjj** [comment]
Awesome. Thanks @michaelklishin.
