### ISSUE TITLE
cassandra-env.sh.erb should use pram.jar_name

### ISSUE THREAD

**Issue by msaffitz** [michaelklishin/cassandra-chef-cookbook#267]
https://github.com/michaelklishin/cassandra-chef-cookbook/blob/master/templates/default/cassandra-env.sh.erb#L193

This assume the jar name as derived from the Cassandra version, should instead directly use the priam.jar_name attribute.

**Comment by michaelklishin** [comment]
@msaffitz feel free to submit a pull request. Thank you.

**Comment by michaelklishin** [comment]
Should be in #268, thank you @msaffitz.
