### ISSUE TITLE
Cloudformation::Opsworks support for CustomJson

### ISSUE THREAD

**Issue by vsudilov** [michaelklishin/cassandra-chef-cookbook#272]
Defining an Opswork stack is convenient to do using cloudformation. Unfortunately, any custom attributes passed from Cloudformation to Opsworks will be cast to string, as per http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-stack.html#cfn-opsworks-stack-custjson:

> 
> Important
> 
> AWS CloudFormation submits all JSON attributes as strings, including any Boolean or number attributes. If you have recipes that expect booleans or numbers, you must modify the recipes to accept strings and to interpret those strings as booleans or numbers.

Would it make sense for this project to do some type checking on attributes? Admittedly this is a bit of an unfortunate thing to support, but maybe the use case justifies it? Any other thoughts for dealing with this issue?

**Comment by michaelklishin** [comment]
By "do some type checking" do you mean "support every parameter value to also be a string"? That sounds like ending maintenance pain.

**Comment by vsudilov** [comment]
Yeah, understood. It seems the most straightforward solution for me is to fork and brute force that myself. Was hoping you'd have another idea.

**Comment by michaelklishin** [comment]
@vsudilov here's (some) hope that OpsWorks will address this issue on their end :/
