### ISSUE TITLE
batch_size_warn_threshold_in_kb issues for Cassandra 1.2.9

### ISSUE THREAD

**Issue by alrf** [michaelklishin/cassandra-chef-cookbook#274]
You have `node.rm('cassandra', 'config', 'batch_size_warn_threshold_in_kb')` if node['cassandra']['version'] < '2.0' condition. 
It's from recipes\config.rb file, line 70.

But when I try to run Cassandra, I get error:

```
INFO [main] 2016-04-07 09:22:31,867 DatabaseDescriptor.java (line 132) Loading settings from file:/usr/local/apache-cassandra-1.2.9/conf1/cassandra.yaml
ERROR [main] 2016-04-07 09:22:32,456 DatabaseDescriptor.java (line 509) Fatal configuration error error
Can't construct a java object for tag:yaml.org,2002:org.apache.cassandra.config.Config; exception=Cannot create property=batch_size_warn_threshold_in_kb for JavaBean=or
g.apache.cassandra.config.Config@69e1968d; Unable to find property 'batch_size_warn_threshold_in_kb' on class: org.apache.cassandra.config.Config
 in "<reader>", line 6, column 1:
    authenticator: org.apache.cassan ...
    ^

```

**Comment by michaelklishin** [comment]
What Cassandra version are you trying to provision?

**Comment by alrf** [comment]
Cassandra 1.2.9

**Comment by michaelklishin** [comment]
Looks like version comparison in this particular case should coerce the value to a float.

**Comment by alrf** [comment]
I use `default['rdt_cassandra']['version'] = '1.2.9'`
similar as here: https://github.com/michaelklishin/cassandra-chef-cookbook/blob/master/attributes/default.rb#L17

**Comment by michaelklishin** [comment]
@alrf feel free to fix the condition and submit a pull request.
