### ISSUE TITLE
Supermarket update and/or release requested

### ISSUE THREAD

**Issue by eric-tucker** [michaelklishin/cassandra-chef-cookbook#286]
Supermarket is at version 4.1.0 and so is the release history.  It's been six months and several commits since the last release.  Any chance for a new release?

**Comment by michaelklishin** [comment]
Yeah, I agree it's time to do a release.

**Comment by bai** [comment]
Friendly bump: would be great to have it uploaded.

**Comment by michaelklishin** [comment]
[4.2.0 is out](https://supermarket.chef.io/cookbooks/cassandra-dse). Thank you @bai for not letting it go under my radar for a few more months :)
