### ISSUE TITLE
Incompatible with Chef 11

### ISSUE THREAD

**Issue by msaffitz** [michaelklishin/cassandra-chef-cookbook#292]
The `node.rm` syntax introduced in 1dc80218e2b75e55ca5bf7a0b4e4fb0a01c1c115 is incapable with Chef < 12.  We have a branch at https://github.com/apptentive-engineering/cassandra-chef-cookbook/tree/chef_11_compat that fixes this but I'm not sure if that's the preferred/best mechanism for removing these attributes.

**Comment by michaelklishin** [comment]
Chef 11 hasn't been updated since April, 2015. I doubt it will see any future development, so it's not a priority to maintain compatibility with it.
