### ISSUE TITLE
OpsCenter fails to restart nodes in cluster: `stderr: sudo: a password is required`

### ISSUE THREAD

**Issue by eyalzek** [michaelklishin/cassandra-chef-cookbook#302]
I'm not sure why this happens, but after upgrading our cluster to the latest versions (using the cookbook `v4.2.0`), attempting to restart a node using the OpsCenter webui fails for a sudo prompt:
`Restarting node IP_OF_NODE failed: /usr/sbin/service dse stop failed exit status: 1 stderr: sudo: a password is required`

The agents running on each node of the cluster are ran with the `cassandra` user, the same as the cassandra process itself... Did anyone face this issue before?

**Comment by cmlicata** [comment]
As far as I know, you should be A) running the agents as root or B) Add the user to the group that owns the directory.
Checkout the troubleshooting FAQs [here](http://www.datastax.com/dev/blog/a-short-troubleshooting-guide-to-opscenter).

**Comment by eyalzek** [comment]
@cmlicata thanks for responding,
the cassandra installation, service and process are all ran by default with the `cassandra` user as specified [here](https://github.com/michaelklishin/cassandra-chef-cookbook/blob/master/attributes/default.rb#L12), and the agent is ran (with the same user)[https://github.com/michaelklishin/cassandra-chef-cookbook/blob/master/recipes/opscenter_agent_datastax.rb#L55] with no option to change to a different user (unless I run cassandra as root as well).

**Comment by cmlicata** [comment]
Perhaps this has to do with your server's sudoer settings?  Hmmm... why don't you try to change the sudoers settings in the system via ```sudo visudo```? 

It may be a timeout on your system (usually about 10 mins).  Take a look at [this](http://askubuntu.com/questions/147241/execute-sudo-without-password) and see how that works for you.

**Comment by eyalzek** [comment]
After further debugging and support from the datastax team, I managed to solve this issue. 
The `datastax-agent` package installs a file: `/etc/sudoers.d/opscenter-agent-sudoers` which gives the relevant permissions to the `cassandra` user (which opscenter is using to perform actions on the cluster). The problem in my case was that the files in `/etc/sudoers.d/` weren't included.
The fix for that is to make sure you have the following line in `/etc/sudoers`:
`#includedir /etc/sudoers.d`

Since I'm using the `sudo` cookbook to handle anything sudo related in my environment, the solution was to set the following attribute before including the `sudo` recipe:
`node['authorization']['sudo']['include_sudoers_d'] = true`

Hope that helps any other people having this problem. I'm closing this issue since it's not related to this cookbook as far as I can tell.

**Comment by michaelklishin** [comment]
@eyalzek thank you for reporting back.
