### ISSUE TITLE
Wrong version of jamm jar with cassandra 3.7 (community)

### ISSUE THREAD

**Issue by eswenson1** [michaelklishin/cassandra-chef-cookbook#304]
With cassandra['version'] set to 3.7, cassandra['install_method'] set to 'tarball', and cassandra['tarball'] set to http://apache.osuosl.org/cassandra/3.7/apache-cassandra-3.7-bin.tar.gz, cookbook sets up incorrect version of jamm JAR file.  cassandra-env.sh references jamm-0.3.1.jar, whereas no such JAR exists in the cassandra tarball.  The version in the tarball is 0.3.0.

**Comment by michaelklishin** [comment]
I believe @wdauchy fixed this in https://github.com/michaelklishin/cassandra-chef-cookbook/commit/2717a48af2305638544d484461ace7898a2116bc.
