### ISSUE TITLE
Add option to override default metric data ttl's

### ISSUE THREAD

**Issue by eyalzek** [michaelklishin/cassandra-chef-cookbook#308]
Hardcoded here:
https://github.com/michaelklishin/cassandra-chef-cookbook/blob/master/templates/default/opscenterd.conf.erb#L47

I would like to tweak this config since the metric data is using up too much disk space on my cluster

**Comment by michaelklishin** [comment]
@eyalzek sounds like a low hanging fruit, feel free to contribute a PR :)
