### ISSUE TITLE
No read permission for jamm jar

### ISSUE THREAD

**Issue by OugiDark** [michaelklishin/cassandra-chef-cookbook#311]
Currently, the config recipe does not set the right permissions for cassandra to be able to read the '/usr/share/java/#{node['cassandra']['jamm']['jar_name']}' file.

This causes cassandra to not start up.
Changing the permission of the file to 0644 fixes the problem, allowing cassandra to start up.

**Comment by michaelklishin** [comment]
@OugiDark feel free to submit a pull request.

**Comment by michaelklishin** [comment]
I see that exactly the same permissions as for jamm are used for JNA and several other files. I doubt that all of them are broken by default: we'd have a flurry of issues reported if this was the case.

So something must be unusual about your setup. I think that configuring read permissions on those files is a good idea, just pointing out that it's not just jamm.
