### ISSUE TITLE
Coding convention

### ISSUE THREAD

**Issue by rhardouin** [michaelklishin/cassandra-chef-cookbook#345]
Hi,

I want to contribute but I see different notations in templates. 

For instances:
- Dot notation in `cassandra.service.erb`: `<%= node.cassandra.user %>`
- Bracket notation in `cassandra.yaml.erb`:  `<%= node['cassandra']['version'] %>`

Can we make a choice and mention it in Contributing section of the README?
This section should also specify other rules - not only for templates.

Thanks!

**Comment by michaelklishin** [comment]
As far as I can see [Chef Style Guide](https://docs.chef.io/ruby.html) only uses the latter. I don't remember where but I believe reading that the dot notation is going away in a future version?
If that's true we should stick to the notation that's not going away ;)

**Comment by rhardouin** [comment]
Indeed, method notation (what I called "dot notation") will be removed in Chef 13.

* https://docs.chef.io/deprecations_attributes.html
* Actually when we run chef with this cookbook we have warnings regardings templates attributes:
```
- /tmp/kitchen/cache/cookbooks/cassandra-dse/recipes/config.rb:266:in `from_file'
  See https://docs.chef.io/deprecations_resource_cloning.html for further details.
 method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at 12 lo
cations:
   - (erubis):22:in `block in evaluate'
   - (erubis):3:in `block in evaluate'
   - (erubis):4:in `block in evaluate'
   - (erubis):6:in `block in evaluate'
   - (erubis):10:in `block in evaluate'
   - (erubis):12:in `block in evaluate'
   - (erubis):13:in `block in evaluate'
   - (erubis):16:in `block in evaluate'
   - (erubis):19:in `block in evaluate'
   - (erubis):20:in `block in evaluate'
   - (erubis):21:in `block in evaluate'
   - (erubis):23:in `block in evaluate'
  See https://docs.chef.io/deprecations_attributes.html for further details.
```

I will make a PR to remove "method access" and add a note in README.
Closing this issue as it's clear we must choose bracket notation.

(Thanks @pdalpra to tell me that `erubis` means templates!)
