### ISSUE TITLE
Use node[:ipaddress] instead of node.ipaddress (Chef 13)

### ISSUE THREAD

**Issue by benthorner** [michaelklishin/cassandra-chef-cookbook#350]
After upgrading to Chef 13, I get the following error when running with seed discovery enabled.

     undefined method `ipaddress' for #<Chef::Node::Attribute:0x000000047b36e0>

**Comment by michaelklishin** [comment]
@benthorner please submit a PR.

**Comment by benthorner** [comment]
I've made a fork, but I'm struggling to get the integration tests passing. Vagrant doesn't seem to work (known VirtualBox networking issue). I've got some of the docker integration tests passing, but I don't have the time to fix everything. What would you like to do?
