### ISSUE TITLE
[:cassandra][:cluster_name] attribute documentation causes error

### ISSUE THREAD

**Issue by wanderanimrod** [michaelklishin/cassandra-chef-cookbook#355]
The README states that the cluster_name is configured by setting the node attribute `node[:cassandra][:cluster_name]`. When I do this, my recipe doesn't converge. The correct way to set the attribute is `node[:cassandra][:config][:cluster_name]`. Am I missing something obvious or this is a real bug in the documentation?

I can submit a pull request to fix that.

**Comment by michaelklishin** [comment]
You [are right](https://github.com/michaelklishin/cassandra-chef-cookbook/blob/master/attributes/config.rb#L1). Please submit a PR that corrects the README?

**Comment by wanderanimrod** [comment]
on it.

**Comment by wanderanimrod** [comment]
PR here https://github.com/michaelklishin/cassandra-chef-cookbook/pull/356
