### ISSUE TITLE
cassandra.yaml changes for latest versions of apache cassandra 3.11

### ISSUE THREAD

**Issue by ankit-agarwal-E1304** [michaelklishin/cassandra-chef-cookbook#384]
New config settings have been added to cassandra.yaml in latest versions of 3.11 like "repair_session_max_tree_depth" in 3.11.6
Is someone maintaining it on this chef cookbook?

**Comment by michaelklishin** [comment]
@ankit-agarwal-E1304 this is open source software, you are welcome to contribute the changes you need. Asking others to do the work *you* need is not how open source works.

**Comment by ankit-agarwal-E1304** [comment]
Thanks for the response @michaelklishin 
I will raise a PR with the desired changes.
