### ISSUE TITLE
Publish the cookbook to the Chef Supermarket

### ISSUE THREAD

**Issue by acqant** [michaelklishin/cassandra-chef-cookbook#91]
I use cassandra I get https://github.com/gbatalski/cassandra

I do berks search cassandra I get

cassandra (0.2.4)
cassandra-opscenter (0.1.0)
cassandra-priam (0.1.3)

**Comment by michaelklishin** [comment]
I'm leaning to use `cassandra-ng` as the name. Not great but still better than `cassandra-and-dse`, `cassandra-dse` or `cassandra2` (which may mislead people when Cassandra 3.0 is out).

Any other ideas?

**Comment by sethrosenblum** [comment]
I'd be in favor of `datastax-cassandra` or `cassandra-datastax`

**Comment by michaelklishin** [comment]
`cassandra-datastax` works for me.

**Comment by kreisys** [comment]
+1. This is the only thing contaminating my Berkfiles :>

**Comment by willejs** [comment]
:+1:

**Comment by michaelklishin** [comment]
Hey, it only took 11 months to fix this!

**Comment by dpkp** [comment]
nice!

**Comment by acqant** [comment]
LOL, what is this cassandra thing you speak of?  

Thanks!
